### ISSUE TITLE
Package api & vue together

### ISSUE THREAD

**Issue by Sigafoos** [exlibris-fed/exlibris#4]
Instead of running on Heroku and Netlify, unite the houses! Then we can start serving pages based on the `Accept` header, maybe.

**Comment by mattgen88** [comment]
This would eliminate the CORS issue, too, if the app and api are on the same domain.

**Comment by mattgen88** [comment]
TODO:

- [x] Serve static with go server
- [ ] Set ENV vars for vue to point to API
- [ ] Clean up routing for API
- [ ] Decommission netlify frontend
- [ ] Point DNS to heroku instead of netlify
- [ ] Set up build system so that go and node hot reload works for a complete development environment
