### ISSUE TITLE
Get rid of Netlify?

### ISSUE THREAD

**Issue by Sigafoos** [exlibris-fed/exlibris#45]
Now that we have #4 is Netlify needed, or will Heroku run both? (of course, Heroku's pay-us-to-use-a-domain system means we should probably find yet a different hosting option for exlibris.social, which is not the same as exlibris-the-software)

**Comment by Sigafoos** [comment]
This is mostly a question for @mattgen88

**Comment by mattgen88** [comment]
To set up a domain they just required me to verify my identity with a CC, we're good to set up exlibris.social on heroku. Point the domain to shrouded-pinchusion-cdzb28x4iwopa3382wtmooxp.herokudns.com, we'll have to figure out TLS again.

**Comment by Sigafoos** [comment]
Just did this.

**Comment by Sigafoos** [comment]
Now that the integration is removed from the repo this is an exlibris.social thing and doesn't concern this repo.
